// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"sync"

	fiber "github.com/gofiber/fiber/v2"
	"github.com/kyh0703/flow/internal/core/handler"
)

type FakeSubFlowHandler struct {
	CaptureStub        func(*fiber.Ctx) error
	captureMutex       sync.RWMutex
	captureArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	captureReturns struct {
		result1 error
	}
	captureReturnsOnCall map[int]struct {
		result1 error
	}
	CreateOneStub        func(*fiber.Ctx) error
	createOneMutex       sync.RWMutex
	createOneArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	createOneReturns struct {
		result1 error
	}
	createOneReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteOneStub        func(*fiber.Ctx) error
	deleteOneMutex       sync.RWMutex
	deleteOneArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	deleteOneReturns struct {
		result1 error
	}
	deleteOneReturnsOnCall map[int]struct {
		result1 error
	}
	GetOneStub        func(*fiber.Ctx) error
	getOneMutex       sync.RWMutex
	getOneArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	getOneReturns struct {
		result1 error
	}
	getOneReturnsOnCall map[int]struct {
		result1 error
	}
	RedoStub        func(*fiber.Ctx) error
	redoMutex       sync.RWMutex
	redoArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	redoReturns struct {
		result1 error
	}
	redoReturnsOnCall map[int]struct {
		result1 error
	}
	TableStub        func() []handler.Mapper
	tableMutex       sync.RWMutex
	tableArgsForCall []struct {
	}
	tableReturns struct {
		result1 []handler.Mapper
	}
	tableReturnsOnCall map[int]struct {
		result1 []handler.Mapper
	}
	UndoStub        func(*fiber.Ctx) error
	undoMutex       sync.RWMutex
	undoArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	undoReturns struct {
		result1 error
	}
	undoReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateOneStub        func(*fiber.Ctx) error
	updateOneMutex       sync.RWMutex
	updateOneArgsForCall []struct {
		arg1 *fiber.Ctx
	}
	updateOneReturns struct {
		result1 error
	}
	updateOneReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSubFlowHandler) Capture(arg1 *fiber.Ctx) error {
	fake.captureMutex.Lock()
	ret, specificReturn := fake.captureReturnsOnCall[len(fake.captureArgsForCall)]
	fake.captureArgsForCall = append(fake.captureArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.CaptureStub
	fakeReturns := fake.captureReturns
	fake.recordInvocation("Capture", []interface{}{arg1})
	fake.captureMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) CaptureCallCount() int {
	fake.captureMutex.RLock()
	defer fake.captureMutex.RUnlock()
	return len(fake.captureArgsForCall)
}

func (fake *FakeSubFlowHandler) CaptureCalls(stub func(*fiber.Ctx) error) {
	fake.captureMutex.Lock()
	defer fake.captureMutex.Unlock()
	fake.CaptureStub = stub
}

func (fake *FakeSubFlowHandler) CaptureArgsForCall(i int) *fiber.Ctx {
	fake.captureMutex.RLock()
	defer fake.captureMutex.RUnlock()
	argsForCall := fake.captureArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) CaptureReturns(result1 error) {
	fake.captureMutex.Lock()
	defer fake.captureMutex.Unlock()
	fake.CaptureStub = nil
	fake.captureReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) CaptureReturnsOnCall(i int, result1 error) {
	fake.captureMutex.Lock()
	defer fake.captureMutex.Unlock()
	fake.CaptureStub = nil
	if fake.captureReturnsOnCall == nil {
		fake.captureReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.captureReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) CreateOne(arg1 *fiber.Ctx) error {
	fake.createOneMutex.Lock()
	ret, specificReturn := fake.createOneReturnsOnCall[len(fake.createOneArgsForCall)]
	fake.createOneArgsForCall = append(fake.createOneArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.CreateOneStub
	fakeReturns := fake.createOneReturns
	fake.recordInvocation("CreateOne", []interface{}{arg1})
	fake.createOneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) CreateOneCallCount() int {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	return len(fake.createOneArgsForCall)
}

func (fake *FakeSubFlowHandler) CreateOneCalls(stub func(*fiber.Ctx) error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = stub
}

func (fake *FakeSubFlowHandler) CreateOneArgsForCall(i int) *fiber.Ctx {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	argsForCall := fake.createOneArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) CreateOneReturns(result1 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	fake.createOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) CreateOneReturnsOnCall(i int, result1 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	if fake.createOneReturnsOnCall == nil {
		fake.createOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) DeleteOne(arg1 *fiber.Ctx) error {
	fake.deleteOneMutex.Lock()
	ret, specificReturn := fake.deleteOneReturnsOnCall[len(fake.deleteOneArgsForCall)]
	fake.deleteOneArgsForCall = append(fake.deleteOneArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.DeleteOneStub
	fakeReturns := fake.deleteOneReturns
	fake.recordInvocation("DeleteOne", []interface{}{arg1})
	fake.deleteOneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) DeleteOneCallCount() int {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	return len(fake.deleteOneArgsForCall)
}

func (fake *FakeSubFlowHandler) DeleteOneCalls(stub func(*fiber.Ctx) error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = stub
}

func (fake *FakeSubFlowHandler) DeleteOneArgsForCall(i int) *fiber.Ctx {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	argsForCall := fake.deleteOneArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) DeleteOneReturns(result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	fake.deleteOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) DeleteOneReturnsOnCall(i int, result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	if fake.deleteOneReturnsOnCall == nil {
		fake.deleteOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) GetOne(arg1 *fiber.Ctx) error {
	fake.getOneMutex.Lock()
	ret, specificReturn := fake.getOneReturnsOnCall[len(fake.getOneArgsForCall)]
	fake.getOneArgsForCall = append(fake.getOneArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.GetOneStub
	fakeReturns := fake.getOneReturns
	fake.recordInvocation("GetOne", []interface{}{arg1})
	fake.getOneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) GetOneCallCount() int {
	fake.getOneMutex.RLock()
	defer fake.getOneMutex.RUnlock()
	return len(fake.getOneArgsForCall)
}

func (fake *FakeSubFlowHandler) GetOneCalls(stub func(*fiber.Ctx) error) {
	fake.getOneMutex.Lock()
	defer fake.getOneMutex.Unlock()
	fake.GetOneStub = stub
}

func (fake *FakeSubFlowHandler) GetOneArgsForCall(i int) *fiber.Ctx {
	fake.getOneMutex.RLock()
	defer fake.getOneMutex.RUnlock()
	argsForCall := fake.getOneArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) GetOneReturns(result1 error) {
	fake.getOneMutex.Lock()
	defer fake.getOneMutex.Unlock()
	fake.GetOneStub = nil
	fake.getOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) GetOneReturnsOnCall(i int, result1 error) {
	fake.getOneMutex.Lock()
	defer fake.getOneMutex.Unlock()
	fake.GetOneStub = nil
	if fake.getOneReturnsOnCall == nil {
		fake.getOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) Redo(arg1 *fiber.Ctx) error {
	fake.redoMutex.Lock()
	ret, specificReturn := fake.redoReturnsOnCall[len(fake.redoArgsForCall)]
	fake.redoArgsForCall = append(fake.redoArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.RedoStub
	fakeReturns := fake.redoReturns
	fake.recordInvocation("Redo", []interface{}{arg1})
	fake.redoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) RedoCallCount() int {
	fake.redoMutex.RLock()
	defer fake.redoMutex.RUnlock()
	return len(fake.redoArgsForCall)
}

func (fake *FakeSubFlowHandler) RedoCalls(stub func(*fiber.Ctx) error) {
	fake.redoMutex.Lock()
	defer fake.redoMutex.Unlock()
	fake.RedoStub = stub
}

func (fake *FakeSubFlowHandler) RedoArgsForCall(i int) *fiber.Ctx {
	fake.redoMutex.RLock()
	defer fake.redoMutex.RUnlock()
	argsForCall := fake.redoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) RedoReturns(result1 error) {
	fake.redoMutex.Lock()
	defer fake.redoMutex.Unlock()
	fake.RedoStub = nil
	fake.redoReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) RedoReturnsOnCall(i int, result1 error) {
	fake.redoMutex.Lock()
	defer fake.redoMutex.Unlock()
	fake.RedoStub = nil
	if fake.redoReturnsOnCall == nil {
		fake.redoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.redoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) Table() []handler.Mapper {
	fake.tableMutex.Lock()
	ret, specificReturn := fake.tableReturnsOnCall[len(fake.tableArgsForCall)]
	fake.tableArgsForCall = append(fake.tableArgsForCall, struct {
	}{})
	stub := fake.TableStub
	fakeReturns := fake.tableReturns
	fake.recordInvocation("Table", []interface{}{})
	fake.tableMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) TableCallCount() int {
	fake.tableMutex.RLock()
	defer fake.tableMutex.RUnlock()
	return len(fake.tableArgsForCall)
}

func (fake *FakeSubFlowHandler) TableCalls(stub func() []handler.Mapper) {
	fake.tableMutex.Lock()
	defer fake.tableMutex.Unlock()
	fake.TableStub = stub
}

func (fake *FakeSubFlowHandler) TableReturns(result1 []handler.Mapper) {
	fake.tableMutex.Lock()
	defer fake.tableMutex.Unlock()
	fake.TableStub = nil
	fake.tableReturns = struct {
		result1 []handler.Mapper
	}{result1}
}

func (fake *FakeSubFlowHandler) TableReturnsOnCall(i int, result1 []handler.Mapper) {
	fake.tableMutex.Lock()
	defer fake.tableMutex.Unlock()
	fake.TableStub = nil
	if fake.tableReturnsOnCall == nil {
		fake.tableReturnsOnCall = make(map[int]struct {
			result1 []handler.Mapper
		})
	}
	fake.tableReturnsOnCall[i] = struct {
		result1 []handler.Mapper
	}{result1}
}

func (fake *FakeSubFlowHandler) Undo(arg1 *fiber.Ctx) error {
	fake.undoMutex.Lock()
	ret, specificReturn := fake.undoReturnsOnCall[len(fake.undoArgsForCall)]
	fake.undoArgsForCall = append(fake.undoArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.UndoStub
	fakeReturns := fake.undoReturns
	fake.recordInvocation("Undo", []interface{}{arg1})
	fake.undoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) UndoCallCount() int {
	fake.undoMutex.RLock()
	defer fake.undoMutex.RUnlock()
	return len(fake.undoArgsForCall)
}

func (fake *FakeSubFlowHandler) UndoCalls(stub func(*fiber.Ctx) error) {
	fake.undoMutex.Lock()
	defer fake.undoMutex.Unlock()
	fake.UndoStub = stub
}

func (fake *FakeSubFlowHandler) UndoArgsForCall(i int) *fiber.Ctx {
	fake.undoMutex.RLock()
	defer fake.undoMutex.RUnlock()
	argsForCall := fake.undoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) UndoReturns(result1 error) {
	fake.undoMutex.Lock()
	defer fake.undoMutex.Unlock()
	fake.UndoStub = nil
	fake.undoReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) UndoReturnsOnCall(i int, result1 error) {
	fake.undoMutex.Lock()
	defer fake.undoMutex.Unlock()
	fake.UndoStub = nil
	if fake.undoReturnsOnCall == nil {
		fake.undoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.undoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) UpdateOne(arg1 *fiber.Ctx) error {
	fake.updateOneMutex.Lock()
	ret, specificReturn := fake.updateOneReturnsOnCall[len(fake.updateOneArgsForCall)]
	fake.updateOneArgsForCall = append(fake.updateOneArgsForCall, struct {
		arg1 *fiber.Ctx
	}{arg1})
	stub := fake.UpdateOneStub
	fakeReturns := fake.updateOneReturns
	fake.recordInvocation("UpdateOne", []interface{}{arg1})
	fake.updateOneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSubFlowHandler) UpdateOneCallCount() int {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	return len(fake.updateOneArgsForCall)
}

func (fake *FakeSubFlowHandler) UpdateOneCalls(stub func(*fiber.Ctx) error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = stub
}

func (fake *FakeSubFlowHandler) UpdateOneArgsForCall(i int) *fiber.Ctx {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	argsForCall := fake.updateOneArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSubFlowHandler) UpdateOneReturns(result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	fake.updateOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) UpdateOneReturnsOnCall(i int, result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	if fake.updateOneReturnsOnCall == nil {
		fake.updateOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubFlowHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.captureMutex.RLock()
	defer fake.captureMutex.RUnlock()
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	fake.getOneMutex.RLock()
	defer fake.getOneMutex.RUnlock()
	fake.redoMutex.RLock()
	defer fake.redoMutex.RUnlock()
	fake.tableMutex.RLock()
	defer fake.tableMutex.RUnlock()
	fake.undoMutex.RLock()
	defer fake.undoMutex.RUnlock()
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSubFlowHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.SubFlowHandler = new(FakeSubFlowHandler)
