import {
  AbortIcon,
  AssignIcon,
  CdrCtrlIcon,
  CdrIcon,
  ChangeServiceIcon,
  ChoiceCallIcon,
  ChoiceMentIcon,
  CloseVRIcon,
  ConsumerMonitIcon,
  CtiCallIcon,
  DBQueryIcon,
  DisSwitchIcon,
  DisconnectIcon,
  DisconnectWebIcon,
  EntityCallIcon,
  GetChannelIcon,
  GetDigitIcon,
  GetPageDataIcon,
  GotoLabelIcon,
  GroupIcon,
  IfIcon,
  IntentCallIcon,
  LogWriteIcon,
  MakeCallIcon,
  MemoIcon,
  MenuCallIcon,
  MenuChangeIcon,
  MenuReturnIcon,
  NLURequestIcon,
  OpenVRIcon,
  PacketCallIcon,
  PacketJsonIcon,
  PacketSizeIcon,
  PlayIcon,
  PushToneIcon,
  RecordIcon,
  RegistServerIcon,
  RequestHTTPIcon,
  RequestPageIcon,
  RequestVRIcon,
  ResponseVRIcon,
  ReturnIcon,
  RouteACDIcon,
  RouteGroupIcon,
  RouteQueueRuleIcon,
  RouteSkillGroupIcon,
  RouteSkillIcon,
  SelectIcon,
  SetEventIcon,
  SetLabelIcon,
  SleepIcon,
  StringParserIcon,
  SubCallIcon,
  SwitchIcon,
  ToneDetectIcon,
  TrackingIcon,
  TransferIcon,
  UnregistServerIcon,
  UserDataIcon,
  UserEnvIcon,
  UserFuncCallIcon,
  UserMenuStatIcon,
  VoiceRecognizeIcon,
  WaitEventIcon,
  WaitInboundIcon,
  WaitOutboundIcon,
  WaitWebInboundIcon,
  type IconButtonProps,
} from '@/app/_components/icon'
import type { FlowType } from '@/models/project'
import type { CustomNodeType } from '@xyflow/react'

export type ComponentItem = {
  title: string
  flowType: FlowType | 'all' // 'all' means it can be used in any flow
  nodeType: CustomNodeType
  isNotInEnd?: boolean // if true, it can't be used in the end node
  icon: React.ComponentType<IconButtonProps>
}

export const components: Record<string, ComponentItem[]> = {
  Telephony: [
    {
      title: 'Play',
      flowType: 'all',
      nodeType: 'Play',
      isNotInEnd: true,
      icon: PlayIcon,
    },
    {
      title: 'Get Digit',
      flowType: 'ivr',
      nodeType: 'GetDigit',
      isNotInEnd: true,
      icon: GetDigitIcon,
    },
    {
      title: 'Wait Inbound',
      flowType: 'ivr',
      nodeType: 'WaitInbound',
      isNotInEnd: true,
      icon: WaitInboundIcon,
    },
    {
      title: 'Wait Outbound',
      flowType: 'ivr',
      nodeType: 'WaitOutbound',
      isNotInEnd: true,
      icon: WaitOutboundIcon,
    },
    {
      title: 'Disconnect',
      flowType: 'all',
      nodeType: 'Disconnect',
      isNotInEnd: true,
      icon: DisconnectIcon,
    },
    {
      title: 'Record',
      flowType: 'ivr',
      nodeType: 'Record',
      isNotInEnd: true,
      icon: RecordIcon,
    },
    {
      title: 'Abort',
      flowType: 'ivr',
      nodeType: 'Abort',
      isNotInEnd: true,
      icon: AbortIcon,
    },
    {
      title: 'Switch',
      flowType: 'ivr',
      nodeType: 'Switch',
      isNotInEnd: true,
      icon: SwitchIcon,
    },
    {
      title: 'DisSwitch',
      flowType: 'ivr',
      nodeType: 'DisSwitch',
      isNotInEnd: true,
      icon: DisSwitchIcon,
    },
    {
      title: 'Transfer',
      flowType: 'all',
      nodeType: 'Transfer',
      isNotInEnd: true,
      icon: TransferIcon,
    },
    {
      title: 'Make Call',
      flowType: 'ivr',
      nodeType: 'MakeCall',
      isNotInEnd: true,
      icon: MakeCallIcon,
    },
    {
      title: 'Get Channel',
      flowType: 'ivr',
      nodeType: 'GetChannel',
      isNotInEnd: true,
      icon: GetChannelIcon,
    },
    {
      title: 'Cti Call',
      flowType: 'ivr',
      nodeType: 'CtiCall',
      icon: CtiCallIcon,
    },
    {
      title: 'Push Tone',
      flowType: 'ivr',
      nodeType: 'PushTone',
      isNotInEnd: true,
      icon: PushToneIcon,
    },
    {
      title: 'Choice Ment',
      flowType: 'ivr',
      nodeType: 'ChoiceMent',
      isNotInEnd: true,
      icon: ChoiceMentIcon,
    },
    {
      title: 'Choice Call',
      flowType: 'ivr',
      nodeType: 'ChoiceCall',
      isNotInEnd: true,
      icon: ChoiceCallIcon,
    },
    {
      title: 'Tone Detect',
      flowType: 'ivr',
      nodeType: 'ToneDetect',
      isNotInEnd: true,
      icon: ToneDetectIcon,
    },
  ],
  VR: [
    {
      title: 'VoiceRecognize',
      flowType: 'ivr',
      nodeType: 'VoiceRecognize',
      isNotInEnd: true,
      icon: VoiceRecognizeIcon,
    },
    {
      title: 'Open VR',
      flowType: 'ivr',
      nodeType: 'OpenVR',
      isNotInEnd: true,
      icon: OpenVRIcon,
    },
    {
      title: 'Close VR',
      flowType: 'ivr',
      nodeType: 'CloseVR',
      icon: CloseVRIcon,
    },
    {
      title: 'Request VR',
      flowType: 'ivr',
      nodeType: 'RequestVR',
      isNotInEnd: true,
      icon: RequestVRIcon,
    },
    {
      title: 'Response VR',
      flowType: 'ivr',
      nodeType: 'ResponseVR',
      isNotInEnd: true,
      icon: ResponseVRIcon,
    },
  ],
  iWeb: [
    {
      title: 'Request Page',
      flowType: 'ivr',
      nodeType: 'RequestPage',
      icon: RequestPageIcon,
    },
    {
      title: 'Get PageData',
      flowType: 'ivr',
      nodeType: 'GetPageData',
      icon: GetPageDataIcon,
    },
    {
      title: 'Regist Server',
      flowType: 'ivr',
      nodeType: 'RegistServer',
      isNotInEnd: true,
      icon: RegistServerIcon,
    },
    {
      title: 'Unregist Server',
      flowType: 'ivr',
      nodeType: 'UnregistServer',
      icon: UnregistServerIcon,
    },
    {
      title: 'Wait Web Inbound',
      flowType: 'ivr',
      nodeType: 'WaitWebInbound',
      isNotInEnd: true,
      icon: WaitWebInboundIcon,
    },
    {
      title: 'Disconnect Web',
      flowType: 'ivr',
      nodeType: 'DisconnectWeb',
      icon: DisconnectWebIcon,
    },
  ],
  AI: [
    {
      title: 'NLU Request',
      flowType: 'ivr',
      nodeType: 'NLURequest',
      isNotInEnd: true,
      icon: NLURequestIcon,
    },
    {
      title: 'Intent Call',
      flowType: 'ivr',
      nodeType: 'IntentCall',
      isNotInEnd: true,
      icon: IntentCallIcon,
    },
    {
      title: 'Entity Call',
      flowType: 'ivr',
      nodeType: 'EntityCall',
      isNotInEnd: true,
      icon: EntityCallIcon,
    },
  ],
  Route: [
    {
      title: 'Route Skill',
      flowType: 'all',
      nodeType: 'RouteSkill',
      icon: RouteSkillIcon,
    },
    {
      title: 'Route Group',
      flowType: 'route',
      nodeType: 'RouteGroup',
      icon: RouteGroupIcon,
    },
    {
      title: 'Route Skill Group',
      flowType: 'all',
      nodeType: 'RouteSkillGroup',
      icon: RouteSkillGroupIcon,
    },
    {
      title: 'User Data',
      flowType: 'all',
      nodeType: 'UserData',
      icon: UserDataIcon,
    },
    {
      title: 'Route ACD',
      flowType: 'all',
      nodeType: 'RouteACD',
      icon: RouteACDIcon,
    },
    {
      title: 'Route QueueRule',
      flowType: 'all',
      nodeType: 'RouteQueueRule',
      icon: RouteQueueRuleIcon,
    },
  ],
  Flow: [
    {
      title: 'If',
      flowType: 'all',
      nodeType: 'If',
      icon: IfIcon,
    },
    {
      title: 'Select',
      flowType: 'all',
      nodeType: 'Select',
      icon: SelectIcon,
    },
    {
      title: 'Assign',
      flowType: 'all',
      nodeType: 'Assign',
      icon: AssignIcon,
    },
    {
      title: 'Menu Call',
      flowType: 'ivr',
      nodeType: 'MenuCall',
      isNotInEnd: true,
      icon: MenuCallIcon,
    },
    {
      title: 'Menu Return',
      flowType: 'ivr',
      nodeType: 'MenuReturn',
      isNotInEnd: true,
      icon: MenuReturnIcon,
    },
    {
      title: 'Sub Call',
      flowType: 'all',
      nodeType: 'SubCall',
      icon: SubCallIcon,
    },
    {
      title: 'Return',
      flowType: 'all',
      nodeType: 'Return',
      isNotInEnd: true,
      icon: ReturnIcon,
    },
    {
      title: 'Change Service',
      flowType: 'ivr',
      nodeType: 'ChangeService',
      isNotInEnd: true,
      icon: ChangeServiceIcon,
    },
    {
      title: 'Menu Change',
      flowType: 'ivr',
      nodeType: 'MenuChange',
      isNotInEnd: true,
      icon: MenuChangeIcon,
    },
    {
      title: 'Sleep',
      flowType: 'all',
      nodeType: 'Sleep',
      icon: SleepIcon,
    },
    {
      title: 'Set Label',
      flowType: 'all',
      nodeType: 'SetLabel',
      icon: SetLabelIcon,
    },
    {
      title: 'GoToLabel',
      flowType: 'all',
      nodeType: 'GotoLabel',
      icon: GotoLabelIcon,
    },
  ],
  Data: [
    {
      title: 'Cdr',
      flowType: 'all',
      nodeType: 'Cdr',
      icon: CdrIcon,
    },
    {
      title: 'Cdr Ctrl',
      flowType: 'ivr',
      nodeType: 'CdrCtrl',
      icon: CdrCtrlIcon,
    },
    // {
    //   title: 'Cdr Call',
    //   flowType: 'all',
    //   nodeType: 'CdrCall',
    //   icon: CdrCallIcon,
    //   isNotInEnd: true,
    // },
    {
      title: 'User Env',
      flowType: 'all',
      nodeType: 'UserEnv',
      icon: UserEnvIcon,
    },
    {
      title: 'String Parser',
      flowType: 'all',
      nodeType: 'StringParser',
      icon: StringParserIcon,
    },
  ],
  UserFunc: [
    {
      title: 'User Function Call',
      flowType: 'all',
      nodeType: 'UserFuncCall',
      icon: UserFuncCallIcon,
    },
  ],
  Database: [
    {
      title: 'DBQuery',
      flowType: 'ivr',
      nodeType: 'DBQuery',
      icon: DBQueryIcon,
    },
  ],
  Log: [
    {
      title: 'Log Write',
      flowType: 'all',
      nodeType: 'LogWrite',
      icon: LogWriteIcon,
    },
  ],
  Event: [
    {
      title: 'Set Event',
      flowType: 'ivr',
      nodeType: 'SetEvent',
      icon: SetEventIcon,
    },
    {
      title: 'Wait Event',
      flowType: 'ivr',
      nodeType: 'WaitEvent',
      icon: WaitEventIcon,
    },
  ],
  Packet: [
    {
      title: 'Packet Call',
      flowType: 'ivr',
      nodeType: 'PacketCall',
      icon: PacketCallIcon,
    },
    {
      title: 'Packet Size',
      flowType: 'ivr',
      nodeType: 'PacketSize',
      icon: PacketSizeIcon,
    },
    {
      title: 'Packet Json',
      flowType: 'all',
      nodeType: 'PacketJson',
      icon: PacketJsonIcon,
    },
    {
      title: 'Request Http',
      flowType: 'ivr',
      nodeType: 'RequestHTTP',
      icon: RequestHTTPIcon,
    },
  ],
  Tracking: [
    {
      title: 'Tracking',
      flowType: 'ivr',
      nodeType: 'Tracking',
      icon: TrackingIcon,
    },
    {
      title: 'Consumer Monit',
      flowType: 'ivr',
      nodeType: 'ConsumerMonit',
      isNotInEnd: true,
      icon: ConsumerMonitIcon,
    },
    {
      title: 'UserMenuStat',
      flowType: 'ivr',
      nodeType: 'UserMenuStat',
      icon: UserMenuStatIcon,
    },
  ],
  Etc: [
    {
      title: 'Memo',
      flowType: 'all',
      nodeType: 'Memo',
      icon: MemoIcon,
    },
    {
      title: 'Group',
      flowType: 'all',
      nodeType: 'Group',
      icon: GroupIcon,
    },
  ],
}
