export const height = {
  header: '64px',
  'autocomplete-item-max-length': '5px',
  'autocomplete-header': '28px',
  'autocomplete-list': '180px',
  'autocomplete-item': '36px',
  'autocomplete-gap': '5px',
  'content-padding': '12px',
  'flow-tab': '48px',
  search: '72px',
  footer: '246px',
  'property-title': '44px',
  'property-tab': '39px',
  'sidebar-title': '62px',
}
