// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/flow/internal/core/domain/model"
	"github.com/kyh0703/flow/internal/core/domain/repository"
)

type FakeAuthRepository struct {
	CreateOneStub        func(context.Context, model.CreateTokenParams) (model.Token, error)
	createOneMutex       sync.RWMutex
	createOneArgsForCall []struct {
		arg1 context.Context
		arg2 model.CreateTokenParams
	}
	createOneReturns struct {
		result1 model.Token
		result2 error
	}
	createOneReturnsOnCall map[int]struct {
		result1 model.Token
		result2 error
	}
	DeleteOneStub        func(context.Context, int64) error
	deleteOneMutex       sync.RWMutex
	deleteOneArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	deleteOneReturns struct {
		result1 error
	}
	deleteOneReturnsOnCall map[int]struct {
		result1 error
	}
	FindOneStub        func(context.Context, int64) (model.Token, error)
	findOneMutex       sync.RWMutex
	findOneArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findOneReturns struct {
		result1 model.Token
		result2 error
	}
	findOneReturnsOnCall map[int]struct {
		result1 model.Token
		result2 error
	}
	FindOneByUserIDStub        func(context.Context, int64) (model.Token, error)
	findOneByUserIDMutex       sync.RWMutex
	findOneByUserIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findOneByUserIDReturns struct {
		result1 model.Token
		result2 error
	}
	findOneByUserIDReturnsOnCall map[int]struct {
		result1 model.Token
		result2 error
	}
	GetListStub        func(context.Context) ([]model.Token, error)
	getListMutex       sync.RWMutex
	getListArgsForCall []struct {
		arg1 context.Context
	}
	getListReturns struct {
		result1 []model.Token
		result2 error
	}
	getListReturnsOnCall map[int]struct {
		result1 []model.Token
		result2 error
	}
	UpdateOneStub        func(context.Context, model.UpdateTokenParams) error
	updateOneMutex       sync.RWMutex
	updateOneArgsForCall []struct {
		arg1 context.Context
		arg2 model.UpdateTokenParams
	}
	updateOneReturns struct {
		result1 error
	}
	updateOneReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthRepository) CreateOne(arg1 context.Context, arg2 model.CreateTokenParams) (model.Token, error) {
	fake.createOneMutex.Lock()
	ret, specificReturn := fake.createOneReturnsOnCall[len(fake.createOneArgsForCall)]
	fake.createOneArgsForCall = append(fake.createOneArgsForCall, struct {
		arg1 context.Context
		arg2 model.CreateTokenParams
	}{arg1, arg2})
	stub := fake.CreateOneStub
	fakeReturns := fake.createOneReturns
	fake.recordInvocation("CreateOne", []interface{}{arg1, arg2})
	fake.createOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthRepository) CreateOneCallCount() int {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	return len(fake.createOneArgsForCall)
}

func (fake *FakeAuthRepository) CreateOneCalls(stub func(context.Context, model.CreateTokenParams) (model.Token, error)) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = stub
}

func (fake *FakeAuthRepository) CreateOneArgsForCall(i int) (context.Context, model.CreateTokenParams) {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	argsForCall := fake.createOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthRepository) CreateOneReturns(result1 model.Token, result2 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	fake.createOneReturns = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) CreateOneReturnsOnCall(i int, result1 model.Token, result2 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	if fake.createOneReturnsOnCall == nil {
		fake.createOneReturnsOnCall = make(map[int]struct {
			result1 model.Token
			result2 error
		})
	}
	fake.createOneReturnsOnCall[i] = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) DeleteOne(arg1 context.Context, arg2 int64) error {
	fake.deleteOneMutex.Lock()
	ret, specificReturn := fake.deleteOneReturnsOnCall[len(fake.deleteOneArgsForCall)]
	fake.deleteOneArgsForCall = append(fake.deleteOneArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.DeleteOneStub
	fakeReturns := fake.deleteOneReturns
	fake.recordInvocation("DeleteOne", []interface{}{arg1, arg2})
	fake.deleteOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthRepository) DeleteOneCallCount() int {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	return len(fake.deleteOneArgsForCall)
}

func (fake *FakeAuthRepository) DeleteOneCalls(stub func(context.Context, int64) error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = stub
}

func (fake *FakeAuthRepository) DeleteOneArgsForCall(i int) (context.Context, int64) {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	argsForCall := fake.deleteOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthRepository) DeleteOneReturns(result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	fake.deleteOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthRepository) DeleteOneReturnsOnCall(i int, result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	if fake.deleteOneReturnsOnCall == nil {
		fake.deleteOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthRepository) FindOne(arg1 context.Context, arg2 int64) (model.Token, error) {
	fake.findOneMutex.Lock()
	ret, specificReturn := fake.findOneReturnsOnCall[len(fake.findOneArgsForCall)]
	fake.findOneArgsForCall = append(fake.findOneArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindOneStub
	fakeReturns := fake.findOneReturns
	fake.recordInvocation("FindOne", []interface{}{arg1, arg2})
	fake.findOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthRepository) FindOneCallCount() int {
	fake.findOneMutex.RLock()
	defer fake.findOneMutex.RUnlock()
	return len(fake.findOneArgsForCall)
}

func (fake *FakeAuthRepository) FindOneCalls(stub func(context.Context, int64) (model.Token, error)) {
	fake.findOneMutex.Lock()
	defer fake.findOneMutex.Unlock()
	fake.FindOneStub = stub
}

func (fake *FakeAuthRepository) FindOneArgsForCall(i int) (context.Context, int64) {
	fake.findOneMutex.RLock()
	defer fake.findOneMutex.RUnlock()
	argsForCall := fake.findOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthRepository) FindOneReturns(result1 model.Token, result2 error) {
	fake.findOneMutex.Lock()
	defer fake.findOneMutex.Unlock()
	fake.FindOneStub = nil
	fake.findOneReturns = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) FindOneReturnsOnCall(i int, result1 model.Token, result2 error) {
	fake.findOneMutex.Lock()
	defer fake.findOneMutex.Unlock()
	fake.FindOneStub = nil
	if fake.findOneReturnsOnCall == nil {
		fake.findOneReturnsOnCall = make(map[int]struct {
			result1 model.Token
			result2 error
		})
	}
	fake.findOneReturnsOnCall[i] = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) FindOneByUserID(arg1 context.Context, arg2 int64) (model.Token, error) {
	fake.findOneByUserIDMutex.Lock()
	ret, specificReturn := fake.findOneByUserIDReturnsOnCall[len(fake.findOneByUserIDArgsForCall)]
	fake.findOneByUserIDArgsForCall = append(fake.findOneByUserIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindOneByUserIDStub
	fakeReturns := fake.findOneByUserIDReturns
	fake.recordInvocation("FindOneByUserID", []interface{}{arg1, arg2})
	fake.findOneByUserIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthRepository) FindOneByUserIDCallCount() int {
	fake.findOneByUserIDMutex.RLock()
	defer fake.findOneByUserIDMutex.RUnlock()
	return len(fake.findOneByUserIDArgsForCall)
}

func (fake *FakeAuthRepository) FindOneByUserIDCalls(stub func(context.Context, int64) (model.Token, error)) {
	fake.findOneByUserIDMutex.Lock()
	defer fake.findOneByUserIDMutex.Unlock()
	fake.FindOneByUserIDStub = stub
}

func (fake *FakeAuthRepository) FindOneByUserIDArgsForCall(i int) (context.Context, int64) {
	fake.findOneByUserIDMutex.RLock()
	defer fake.findOneByUserIDMutex.RUnlock()
	argsForCall := fake.findOneByUserIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthRepository) FindOneByUserIDReturns(result1 model.Token, result2 error) {
	fake.findOneByUserIDMutex.Lock()
	defer fake.findOneByUserIDMutex.Unlock()
	fake.FindOneByUserIDStub = nil
	fake.findOneByUserIDReturns = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) FindOneByUserIDReturnsOnCall(i int, result1 model.Token, result2 error) {
	fake.findOneByUserIDMutex.Lock()
	defer fake.findOneByUserIDMutex.Unlock()
	fake.FindOneByUserIDStub = nil
	if fake.findOneByUserIDReturnsOnCall == nil {
		fake.findOneByUserIDReturnsOnCall = make(map[int]struct {
			result1 model.Token
			result2 error
		})
	}
	fake.findOneByUserIDReturnsOnCall[i] = struct {
		result1 model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) GetList(arg1 context.Context) ([]model.Token, error) {
	fake.getListMutex.Lock()
	ret, specificReturn := fake.getListReturnsOnCall[len(fake.getListArgsForCall)]
	fake.getListArgsForCall = append(fake.getListArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetListStub
	fakeReturns := fake.getListReturns
	fake.recordInvocation("GetList", []interface{}{arg1})
	fake.getListMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthRepository) GetListCallCount() int {
	fake.getListMutex.RLock()
	defer fake.getListMutex.RUnlock()
	return len(fake.getListArgsForCall)
}

func (fake *FakeAuthRepository) GetListCalls(stub func(context.Context) ([]model.Token, error)) {
	fake.getListMutex.Lock()
	defer fake.getListMutex.Unlock()
	fake.GetListStub = stub
}

func (fake *FakeAuthRepository) GetListArgsForCall(i int) context.Context {
	fake.getListMutex.RLock()
	defer fake.getListMutex.RUnlock()
	argsForCall := fake.getListArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthRepository) GetListReturns(result1 []model.Token, result2 error) {
	fake.getListMutex.Lock()
	defer fake.getListMutex.Unlock()
	fake.GetListStub = nil
	fake.getListReturns = struct {
		result1 []model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) GetListReturnsOnCall(i int, result1 []model.Token, result2 error) {
	fake.getListMutex.Lock()
	defer fake.getListMutex.Unlock()
	fake.GetListStub = nil
	if fake.getListReturnsOnCall == nil {
		fake.getListReturnsOnCall = make(map[int]struct {
			result1 []model.Token
			result2 error
		})
	}
	fake.getListReturnsOnCall[i] = struct {
		result1 []model.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthRepository) UpdateOne(arg1 context.Context, arg2 model.UpdateTokenParams) error {
	fake.updateOneMutex.Lock()
	ret, specificReturn := fake.updateOneReturnsOnCall[len(fake.updateOneArgsForCall)]
	fake.updateOneArgsForCall = append(fake.updateOneArgsForCall, struct {
		arg1 context.Context
		arg2 model.UpdateTokenParams
	}{arg1, arg2})
	stub := fake.UpdateOneStub
	fakeReturns := fake.updateOneReturns
	fake.recordInvocation("UpdateOne", []interface{}{arg1, arg2})
	fake.updateOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthRepository) UpdateOneCallCount() int {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	return len(fake.updateOneArgsForCall)
}

func (fake *FakeAuthRepository) UpdateOneCalls(stub func(context.Context, model.UpdateTokenParams) error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = stub
}

func (fake *FakeAuthRepository) UpdateOneArgsForCall(i int) (context.Context, model.UpdateTokenParams) {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	argsForCall := fake.updateOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthRepository) UpdateOneReturns(result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	fake.updateOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthRepository) UpdateOneReturnsOnCall(i int, result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	if fake.updateOneReturnsOnCall == nil {
		fake.updateOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	fake.findOneMutex.RLock()
	defer fake.findOneMutex.RUnlock()
	fake.findOneByUserIDMutex.RLock()
	defer fake.findOneByUserIDMutex.RUnlock()
	fake.getListMutex.RLock()
	defer fake.getListMutex.RUnlock()
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.AuthRepository = new(FakeAuthRepository)
